.pre-commit-hooks.yaml

Don't run roxygen hook on every file individually

---

.pre-commit-hooks.yaml
DESCRIPTION
R/infra.R
README.Rmd
README.md
bin/spell-check
inst/WORDLIST
man/run_test.Rd
man/run_test_impl.Rd
tests/testthat/in/spell-check-fail.md
tests/testthat/in/spell-check-ignored-success.md
tests/testthat/in/spell-check-language-success.md
tests/testthat/in/spell-check-success.md
tests/testthat/in/spell-check-wordlist-success.md
tests/testthat/test-all.R

Feature spell check

---

.pre-commit-hooks.yaml
README.Rmd
README.md
bin/deps-in-desc
bin/spell-check
tests/testthat/in/deps-in-desc-fail.R
tests/testthat/in/deps-in-desc-success.R
tests/testthat/reference-objects/DESCRIPTION
tests/testthat/test-all.R

Feature deps in desc

---

inst/bin/readme-rmd-rendered

don't fail if there is no rmd readme

---

README.Rmd
README.md

tell people how to uninstall

---

DESCRIPTION

Move imports to suggests

---

inst/bin/style-files

require styler 1.2 from CRAN

---

vignettes/hook-arguments.Rmd

Better hook documentation

---

vignettes/manual-installation.Rmd

Improve manual installation vignette

---

.pre-commit-hooks.yaml
inst/pre-commit-config.yaml
vignettes/available-hooks.Rmd

doc codemeta order

---

.pre-commit-hooks.yaml

Do not process in parallel for hook spell check

---

.pre-commit-config.yaml
DESCRIPTION
inst/consistent_release_tag
inst/pre-commit-config.yaml

Also tie version of precommit hooks to package version.

More version checks

---

vignettes/FAQ.Rmd
vignettes/available-hooks.Rmd
vignettes/hook-arguments.Rmd
vignettes/manual-installation.Rmd
vignettes/why-use-hooks.Rmd

Reviewed the vignettes and addressed minor grammar & typo issues.

Update pkg vignettes

---

NEWS.md
R/setup.R

Create r-reticulate if not existant

---

.pre-commit-config.yaml
NEWS.md
inst/WORDLIST
inst/pre-commit-config.yaml

make sure each file has exactly one trailing line

---

.pre-commit-config.yaml
NEWS.md
inst/WORDLIST
inst/bin/spell-check
inst/pre-commit-config.yaml

Minor fixes for spell checker

---

DESCRIPTION
R/config.R
R/testing.R
inst/WORDLIST
tests/testthat/test-conda.R
tests/testthat/test-config.R

Fix usethis 1.6

---

R/install.R
R/utils.R
_pkgdown.yml
inst/WORDLIST

Add search

---

.pre-commit-hooks.yaml
NEWS.md
inst/WORDLIST
inst/bin/spell-check
inst/pre-commit-hooks.yaml
tests/testthat/test-all.R
vignettes/available-hooks.Rmd

Consistency for excluding files

---

DESCRIPTION
NEWS.md
_pkgdown.yml
inst/WORDLIST

Closes #154. @pat-s like this?

Add pkgdown link

---

DESCRIPTION
R/call.R
R/config.R
R/exec.R
R/install.R
R/open.R
R/roxygen2.R
R/setup.R
man/autoupdate.Rd
man/call_and_capture.Rd
man/diff_requires_run_roxygenize.Rd
man/install_precommit.Rd
man/open_config.Rd
man/path_precommit_exec.Rd
man/precommit-package.Rd
man/uninstall_precommit.Rd
man/use_precommit.Rd
man/use_precommit_config.Rd

improvements for passing R CMD Check

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
DESCRIPTION
NEWS.md
inst/WORDLIST
inst/bin/style-files
inst/consistent-release-tag
inst/pre-commit-hooks.yaml
vignettes/available-hooks.Rmd

More flexibility to specify styler style

---

NEWS.md
R/setup.R

fix install_hooks 

---

R/config.R

Write Rbuildignore file to given root

---

NEWS.md
R/install.R
tests/testthat/test-conda.R

Make sure line is remove without promt and test it

---

tests/testthat/test-assumptions.R

Drop assumption test fixed in #191

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
DESCRIPTION
inst/WORDLIST
inst/bin/style-files
inst/consistent-release-tag
inst/pre-commit-hooks.yaml
vignettes/available-hooks.Rmd

Closes #196. Needs tests and TODO fixes.

Allow updating and version check from R API

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
DESCRIPTION
inst/WORDLIST
inst/bin/style-files
inst/consistent-release-tag
inst/pre-commit-hooks.yaml
vignettes/available-hooks.Rmd

Because of #195, We'll revert #183 and re-implement #178 later with the approach outlined in #195.

Revert #183

---

DESCRIPTION
NEWS.md
cran-comments.md
inst/pre-commit-config-pkg.yaml
inst/pre-commit-config-proj.yaml

Release  v0.1.3

---

R/exec.R
tests/testthat/test-exec.R

Proper pip path derivation on Windows

---

.pre-commit-hooks.yaml
NEWS.md
R/testing.R
inst/WORDLIST
inst/bin/deps-in-desc
inst/pre-commit-hooks.yaml
man/run_test.Rd
man/run_test_impl.Rd
tests/testthat/in/deps-in-desc-fail.Rmd
tests/testthat/in/deps-in-desc-fail.Rnw
tests/testthat/in/deps-in-desc-success.Rmd
tests/testthat/in/deps-in-desc-success.Rnw
tests/testthat/test-all.R

support rnw, rmd and .Rprofile for deps-in-desc hook

---

README.Rmd
README.md

List dev + release on README

---

R/exec.R
README.Rmd
README.md
man/path_derive_precommit_exec.Rd

Reverse search order for speed in executable

---

R/testing.R
man/run_test.Rd
man/run_test_impl.Rd

This is a pre-test to figure out what's wrong with #225 on windows.

extend capabilities of run_test to take env and sterr msg

---

vignettes/available-hooks.Rmd

Add --no-warn-cache to docs

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
NEWS.md
inst/WORDLIST
inst/pre-commit-config-pkg.yaml
inst/pre-commit-config-proj.yaml
inst/pre-commit-hooks.yaml
tests/testthat/test-assumptions.R
tests/testthat/test-hooks-regex-exclude.R

Ignore 
* renv.lock for spelling
* renv/activate.R for styling
* renv/settings.dcf for spelling.
* renv/activate.R for deps-in-desc.

Better {renv} filtering

---

README.Rmd
README.md
inst/bin/style-files

Don't fail on styler warning

---

R/testing.R
inst/bin/style-files

Promote all but uninitialised column warning to error

---

inst/bin/roxygenize
inst/bin/style-files

Require higher package versions

---

inst/hooks/exported/roxygenize.R
inst/hooks/exported/style-files.R

Advise to install specific version to allow breaking changes in develpment

Improve install instruction

---

renv.lock
renv/activate.R

Use own {renv} fork that should fix https://github.com/rstudio/renv/issues/837 and then also update some other packages.

Fix concurrency

---

R/install.R
tests/testthat/test-conda.R

unpin python 3.9

---

R/config.R
R/exec.R
R/install.R
R/utils.R
tests/testthat/test-conda.R
tests/testthat/test-config.R
tests/testthat/test-setup.R
tests/testthat/test-zzz.R

locate pre-commit executable on macOs build with pip

---

.pre-commit-config.yaml
DESCRIPTION
NEWS.md
inst/hooks/exported/style-files.R
tests/testthat/test-hooks.R

More informative error on missing dependency

---

NEWS.md
R/roxygen2.R
R/setup.R
tests/testthat/test-hook-roxygenize.R
vignettes/ci.Rmd

simplify roxygen problem handling

---

vignettes/why-use-hooks.Rmd

document advantages of pre-commit

---

R/utils.R

return NA if rev for my repo can't be read

---

DESCRIPTION
R/testing.R
man/git_init.Rd
man/hook_state_assert.Rd
man/run_test.Rd
man/run_test_impl.Rd
tests/testthat/test-hook-roxygenize.R
tests/testthat/test-hooks.R

Fix R CMD check fail

---

NEWS.md
R/setup.R
tests/testthat/test-setup.R

Don't do anything when autoudpate is required with renv incompat

---

DESCRIPTION
NEWS.md
cran-comments.md
inst/pre-commit-config-pkg.yaml
inst/pre-commit-config-proj.yaml
vignettes/FAQ.Rmd
vignettes/available-hooks.Rmd
vignettes/ci.Rmd
vignettes/hook-order.Rmd
vignettes/precommit.Rmd
vignettes/testing.Rmd
vignettes/why-use-hooks.Rmd

Diff to previous release: https://github.com/lorenzwalthert/precommit/compare/v0.2.2.9019...v0.3.0

Release v0.3.0

---

.pre-commit-config.yaml
DESCRIPTION
NEWS.md
inst/pre-commit-config-pkg.yaml
inst/pre-commit-config-proj.yaml

To adress https://github.com/pre-commit-ci/issues/issues/123. cc: @pat-s

Validate pre-commit.ci config to avoid local pass and ci fail

---

.github/workflows/hook-tests-legacy.yml
.github/workflows/hook-tests.yaml
NEWS.md

Never install from source in CI

---

NEWS.md
inst/hooks/exported/parsable-R.R
tests/testthat/test-hooks.R

more context for `parsable-R`

---

DESCRIPTION
NEWS.md
R/zzz.R
cran-comments.md
inst/pre-commit-config-pkg.yaml
inst/pre-commit-config-proj.yaml

Prepare for release:
Submit to CRAN:
Wait for CRAN...

Release v0.3.2

---

.pre-commit-hooks.yaml
NEWS.md
inst/pre-commit-hooks.yaml

Also style quarto docs

---

R/config.R

Fix error message

---

DESCRIPTION
R/testing.R

remove {digest} dependency

---

NEWS.md
renv.lock
renv/activate.R

Hook dependency updates

---

renv.lock
renv/activate.R

Downgrade renv to avoid performance perks

---

inst/hooks/exported/spell-check.R

Relevant comment: https://github.com/lorenzwalthert/precommit/pull/511#issuecomment-1719383237

Make sorting consistent with spelling::update_wordlist

---

R/roxygen2.R
inst/hooks/exported/roxygenize.R
man/roxygenize_with_cache.Rd
tests/testthat/test-hook-roxygenize.R

Only rely on git diff if files have changed

---

.github/workflows/hook-dependencies-update.yml
.pre-commit-config.yaml
inst/update-ppm-url.R
renv.lock

Rely on specific date to ensure archived binaries are still present

---

.github/workflows/hook-dependencies-update.yml
.pre-commit-config.yaml
inst/update-dependency-graph-existing-packages.R
inst/update-existing-hook-dependencies.R
inst/update-renv-prepare.R
renv.lock

Fix hook dependency updates

---

.pre-commit-config.yaml
DESCRIPTION
NEWS.md
cran-comments.md
inst/pre-commit-config-pkg.yaml
inst/pre-commit-config-proj.yaml

Prepare for release:
Perform release:
Wait for CRAN...

Release {precommit} 0.4.2

---

DESCRIPTION
NEWS.md
R/testing.R
cran-comments.md
inst/WORDLIST
inst/pre-commit-config-pkg.yaml
inst/pre-commit-config-proj.yaml
tests/testthat/test-hook-codemeta-description-updated.R
tests/testthat/test-hook-deps-in-desc-R.R
tests/testthat/test-hook-lintr.R
tests/testthat/test-hook-parsable-R.R
tests/testthat/test-hook-readme-rmd-rendered.R
tests/testthat/test-hook-roxygenize.R
tests/testthat/test-hook-spell-check.R
tests/testthat/test-hook-style-files.R

Prepare for release:
Perform release:
Wait for CRAN...

Release {precommit} 0.4.3
