.Rbuildignore, .pre-commit-config.yaml, README.Rmd, README.md, inst/consistent_release_tag, inst/consistent_release_tag.sh, inst/pre-commit-config.yaml
Closes #18, although not automatically creating the releases in CI, but make sure when we push, the tags work.
=> Ensure revision correspondence of config file and git tag

.pre-commit-config.yaml, R/config.R, R/release.R, R/setup.R, R/utils.R, inst/WORDLIST, inst/consistent-release-tag, inst/pre-commit-config-pkg.yaml, inst/pre-commit-config-proj.yaml, man/set_path_cp_config_from.Rd, man/use_precommit.Rd, man/use_precommit_config.Rd, tests/testthat/test-conda.R, tests/testthat/test-config.R
Closes #142. First all read-only hooks, then all write and read hooks for speed.
=> Use more thoughtful order for hooks, between pkg and project

NEWS.md, R/call.R, R/exec.R, R/install.R, R/setup.R, R/utils.R, man/install_precommit.Rd, man/path_derive_precommit_exec_conda.Rd, man/uninstall_precommit.Rd, tests/testthat/test-utils.R, vignettes/available-hooks.Rmd
Closes #146. Offers isolation from other envs. The key was to use `conda run -n r-precommit /path/to/exec` instead of `/path/to/exec` whenever we need the executable if the installation method was conda (which can be checked from the pre-commit executable path).
=> Switch to env r-precommit

NEWS.md, inst/WORDLIST, inst/bin/roxygenize
Closes #171. Should only be merged after CRAN release.
=> Better roxygen2 cache

.github/workflows/R-CMD-check.yaml, DESCRIPTION, inst/WORDLIST, tests/testthat/test-assumptions.R
Prefer conda binary from miniconda over system as suggested in https://github.com/rstudio/reticulate/issues/793.
=> Add macOS CI again for conda

DESCRIPTION, R/config.R, tests/testthat/test-config.R
Seems like missing unit tests for #189 got us. `{usethis}` 2.0.0 contains a fix to our workaround for https://github.com/r-lib/usethis/issues/1125, so the workaround fails (at least locally for me, let's see what GitHub Actions say). A unit test would have caused their rev-dep checks to fail and let us fix the problem in advance. I think I should really put some effort into easily maintainable testing infra. -.- 
cc: @krzyslom
=> Fix .Rbuildignore writing with usethis 2.0.0

NEWS.md, R/exec.R
Homebrew installs pre-commit to `/opt/hombrew/bin` on the new M1 chips
Fixes #239
=> Add pre-commit location for Apple Silicon Homebrew

.github/workflows/hook-tests-legacy.yml, .github/workflows/hook-tests.yaml, NEWS.md, renv.lock, vignettes/testing.Rmd
Closes #263. This test for `v0.1.3` hook scripts and associated tests. We'll have to see if we ever want to require up-to-date hook revision for up-to-date {precommit}.
=> Test legacy hook scripts

NEWS.md, R/exec.R, R/install.R, R/update.R, README.Rmd, README.md, man/path_derive_precommit_exec.Rd, tests/testthat/test-exec.R
Closes #265. This will be important when people try to upgrade their pre-commit executable.
=> Check for multiple executables

NEWS.md, renv.lock, renv/activate.R
Otherwise, installation times out on pre-commit.ci, e.g. https://github.com/lorenzwalthert/precommit/pull/314
This removes a total of 12 packages from 71.
=> Cut down on dependencies

.gitignore, .pre-commit-hooks.yaml, inst/hooks/exported/parsable-R.R, inst/pre-commit-hooks.yaml, tests/testthat/in/parsable-R-fail.Rmd, tests/testthat/in/parsable-R-success.Rmd, tests/testthat/test-all.R, tests/testthat/test-hooks.R, vignettes/available-hooks.Rmd
=> Add  Rmarkdown files to parsable-R hook

NEWS.md, inst/hooks/exported/deps-in-desc.R, tests/testthat/in/README.Rmd, tests/testthat/test-hooks.R, vignettes/available-hooks.Rmd
=> Don't check readme.Rmd

NEWS.md, R/cache.R, vignettes/available-hooks.Rmd
=> Add deprecation note

.pre-commit-hooks.yaml, inst/hooks/exported/codemeta-description-updated, inst/hooks/exported/codemeta-description-updated.R, inst/pre-commit-hooks.yaml, tests/testthat/test-hooks.R
=> make hook `language: r` and write test

DESCRIPTION, R/setup.R, tests/testthat/test-setup.R
=> exclude R from roxygen snippet generation

NEWS.md, renv/activate.R
=> use latest renv

R/purl.R, tests/testthat/in/parsable-R-success.Rmd
Closes #381. See also for both parsable R and deps in desc hook:
https://github.com/r-lib/styler/runs/5419721151?check_suite_focus=true
=> Ignore non-R chunks in robust purling

.github/workflows/pkgdown.yaml
Use a newer pkgdown action to also build page on any PR (but only deploys on default branch). This mitigates the problem that a PR succeeds without a pkgdown dry run fail once merged.
=> Build pkgdown and fail on PR

.pre-commit-config.yaml, inst/pre-commit-config-pkg.yaml, inst/pre-commit-config-proj.yaml, tests/testthat/reference-objects/pre-commit-config.yaml
Before you merge, maybe check out whether there is/was a reason for these lines:
https://github.com/lorenzwalthert/precommit/blob/fcecc1049dbbcdbf2a6662ba295760323f804536/inst/pre-commit-hooks.yaml#L106
they could be written
``` yaml
files: '\.(...)$'
```
:question: There are a few like that in other places too. Whatever the reason, the changes here worked for me on [this commit](https://github.com/ropenscilabs/deposits/commit/957410a442b6dbf8249ae6af5e9d8a8301974b9d) which accepted a bunch of `data.Rds.R`-type filenames:rocket:
=> update regex patterns for forbid_to_commit; fixes #409

NEWS.md, R/setup.R
@lorenzwalthert Easy to reproduce the :bug: behind this one:
1. Go to a directory anywhere that is not an R package and/or does not have a `pre-commit-config.yaml` file
2. Start R
3. type `library(precommit)` and watch it error
----
Another question for you here, before i open a hopefully unnecessary issue: I have entirely broken `precommit` (this package, not the python one) by manually removing all cached `renv` directories, and removing `~/.cache/R/R.cache`. precommit now fails to find any renv-ed versions of `desc`, `styler`, `docopt`, whatever. I've tried removing and reinstalling everything, but no matter what I do precommit fails to reestablish its renv. Any quick tips? Or shall i open an issue?
=> don't presume pre-commit-config exists in ensure_renv_compat

API, DESCRIPTION, NEWS.md, R/roxygen2.R, inst/hooks/exported/codemeta-description-updated.R, inst/hooks/exported/roxygenize.R, inst/hooks/exported/use-tidy-description.R, man/diff_requires_run_roxygenize.Rd, man/extract_diff_root.Rd, man/git_init.Rd, tests/testthat/test-hooks.R, vignettes/available-hooks.Rmd
See: https://github.com/lorenzwalthert/precommit/pull/432
I seem to get a docopt issue when specifying an option without any arguments. See: https://github.com/lorenzwalthert/precommit/issues/429#issuecomment-1179806044. 
Therefore, I added <_ignored>... arguments as a workaround. I bet there is a better solution, but I wanted to get this initial commit out quickly.
I am unsure what is wrong with my new roxygenize tests.
=> Support --root for more hooks

renv.lock
In particular removes tibble {dependency} and {rematch2} since {styler} does not have those anymore.
=> dependency updates

inst/pre-commit-config-pkg.yaml, inst/pre-commit-config-proj.yaml
Hi, 
Feel free to remove this pull request, but I just installed the `R` package and saw that the spelling of `required` was incorrect in two of the example yaml configurations.  So this PR just fixes the spelling  in those cases.
=> Updated spelling of required

inst/hooks/exported/roxygenize.R
roxygenise is never triggered anymore. A regression introduced with exposed root arguments for hooks.
=> Fix roxygenise cache invalidation

.pre-commit-config.yaml
See also #453 which corrected this typo in the files in the inst folder.
I noticed this typo in my config file after using `precommit::use_precommit()` to setup pre-commit for my R package, and then found out that this was mostly likely fixed by #453 but didn't make it to a new release yet (still using 0.3.2, and changes on main since then [here](https://github.com/lorenzwalthert/precommit/compare/v0.3.2...main indicate it was fixed since then) ). However, when searching for the string in question I found another instance of it in the precommit config file used by the project itself. I thought you might want to correct that as well, hence this PR. ^^ 
Additional note, when saving the file my editor removed a lot of trailing spaces automatically. I did not add that to this commit, but …
=> ✏️Correct typo of required in comment in .pre-commit-config.yml

vignettes/available-hooks.Rmd
Corrects warning argument by changing dash to underscore
=> correct typo from dash to underscore

R/testing.R, man/run_test.Rd, man/run_test_impl.Rd, vignettes/hook-order.Rmd
@lorenzwalthert please let me know if that's what you had in mind in https://github.com/lorenzwalthert/precommit/pull/511#pullrequestreview-1627271314
=> Add read_only flag to run_test

DESCRIPTION, R/cache.R, R/release.R, man/may_require_permanent_cache.Rd, man/update_rev_in_config.Rd, tests/testthat/test-hook-roxygenize.R, tests/testthat/test-hooks.R
Closes #535. Need to update lock file to contain latest {roxygen2} release, which is not installed currently in hook tests (they fail therefore) and on windows (with {pak} since installs binaries), then, the errors will go away.
=> House keeping

.pre-commit-config.yaml, DESCRIPTION, NEWS.md, R/config.R, R/release.R, R/roxygen2.R, R/setup.R, R/utils.R, cran-comments.md, inst/WORDLIST, inst/pre-commit-config-pkg.yaml, inst/pre-commit-config-proj.yaml, tests/testthat/test-hook-roxygenize.R, tests/testthat/test-hooks.R, tests/testthat/test-setup.R
Since {styler} needs to be updated on CRAN due to changes in parser error messages (https://github.com/r-lib/styler/pull/1183), and [#1176](https://github.com/r-lib/styler/pull/1176) breaks {precommit} tests, a new {precommit} release must preceed a new {styler} release.
Prepare for release:
Perform release:
Wait for CRAN...
=> Release {precommit} 0.4.1

.pre-commit-hooks.yaml, inst/pre-commit-hooks.yaml, tests/testthat/in/lintr-fail.qmd, tests/testthat/in/lintr-success.qmd, tests/testthat/test-hook-lintr.R
=> feat: lint .qmd docs

.pre-commit-hooks.yaml, DESCRIPTION, inst/hooks/exported/parsable-roxygen.R, inst/pre-commit-hooks.yaml, tests/testthat/in/parsable-roxygen-fail.R, tests/testthat/in/parsable-roxygen-fail2.R, tests/testthat/in/parsable-roxygen-success.R, tests/testthat/reference-objects/pre-commit-config.yaml, tests/testthat/test-hook-parsable-roxygen.R, vignettes/available-hooks.Rmd
As discussed in #562.
Things to note:
* Since `roxygen2::parse_file()` [does actually parse the file](https://github.com/r-lib/roxygen2/blob/c03a6711eea3f7dc16e55f0ab0babac9ff40d9ea/R/tokenize.R#L21), I think we have to allow this hook to fail in two ways:
- If it catches a warning, it fails and explains that it's due to a roxygen error
- If it catches an error, it fails in the same way as `parsable-R`
* I don't _think_ we need to actually evaluate the code though, hence [`roxygen2::parse_file(..., env = NULL)`](https://roxygen2.r-lib.org/reference/parse_package.html#arguments) - unless you can think of some reason why we _would_ need to evaluate?
* Do we need to do anything to ensure that {roxygen2} is available?
---
Closes #562.
=> Add parsable-roxygen hook

inst/pre-commit-gha.yaml
Version 18.04 has been removed from Github Actions in favor of newer releases.
Fixes issue #592
=> fix: Update ubuntu to version 22.04

.pre-commit-config.yaml, R/roxygen2.R, precommit.Rproj
=> Re-instantiate roxygen error message
